#!/bin/bash
set -euo pipefail

# Redirect all output to a logfile and keep stdout/stderr visible
exec > >(tee -a /var/log/user-data.log) 2>&1

# Template variables injected by Terraform
ANSIBLE_PASSWORD_SECRET_NAME="${ansible_password_secret_name}"
AWS_REGION="${aws_region}"

log() { printf "%s %s\n" "$(date -u +'%Y-%m-%dT%H:%M:%SZ')" "$*"; }
step_complete() { log "STEP_COMPLETE: $1"; echo "STEP_COMPLETE: $1" >> /var/log/user-data-steps.log; }

trap 'log "ERROR: user-data aborted at line $${LINENO}"; echo "ERROR at line $${LINENO}" >> /var/log/user-data-steps.log; exit 1' ERR

log "Starting Semaphore server user-data"

step="update-packages"
log "STEP: $${step} - updating apt and upgrading packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
step_complete "$${step}"

step="ssm-agent"
log "STEP: $${step} - SSM agent handling"
if snap list amazon-ssm-agent >/dev/null 2>&1; then
    log "SSM agent present via snap"
    snap start amazon-ssm-agent || log "snap start returned non-zero"
else
    log "SSM agent not in snap; attempting dpkg install (non-fatal)"
    wget -q https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb || log "wget failed"
    dpkg -i amazon-ssm-agent.deb || log "dpkg install returned non-zero"
    systemctl enable amazon-ssm-agent || log "systemctl enable failed"
    systemctl start amazon-ssm-agent || log "systemctl start failed"
fi
step_complete "$${step}"

step="install-dependencies"
log "STEP: $${step} - installing dependencies"
apt-get install -y --no-install-recommends \
    git curl wget ca-certificates unzip jq vim nano \
    ansible openssh-client python3-pip awscli
step_complete "$${step}"

step="download-semaphore"
log "STEP: $${step} - downloading Ansible Semaphore"
SEMAPHORE_VERSION="2.10.22"
wget -q "https://github.com/ansible-semaphore/semaphore/releases/download/v$${SEMAPHORE_VERSION}/semaphore_$${SEMAPHORE_VERSION}_linux_amd64.deb"
dpkg -i "semaphore_$${SEMAPHORE_VERSION}_linux_amd64.deb"
step_complete "$${step}"

step="create-semaphore-user"
log "STEP: $${step} - creating semaphore user"
useradd -r -m -d /opt/semaphore -s /bin/bash semaphore || log "User already exists"
mkdir -p /opt/semaphore
chown -R semaphore:semaphore /opt/semaphore
step_complete "$${step}"

step="configure-semaphore"
log "STEP: $${step} - configuring Semaphore"
cat > /opt/semaphore/config.json <<'EOF'
{
  "mysql": {
    "host": "",
    "user": "",
    "pass": "",
    "name": ""
  },
  "bolt": {
    "host": "/opt/semaphore/semaphore.db"
  },
  "port": ":3000",
  "interface": "0.0.0.0",
  "tmp_path": "/tmp/semaphore",
  "cookie_hash": "$(openssl rand -base64 32)",
  "cookie_encryption": "$(openssl rand -base64 32)",
  "access_key_encryption": "$(openssl rand -base64 32)",
  "email_sender": "",
  "email_host": "",
  "email_port": "",
  "email_username": "",
  "email_password": "",
  "email_secure": false,
  "web_host": "",
  "ldap_binddn": "",
  "ldap_bindpassword": "",
  "ldap_server": "",
  "ldap_searchdn": "",
  "ldap_searchfilter": "",
  "ldap_mappings": {
    "dn": "",
    "mail": "",
    "uid": "",
    "cn": ""
  },
  "telegram_chat": "",
  "telegram_token": "",
  "concurrency_mode": "",
  "max_parallel_tasks": 0,
  "email_alert": false,
  "telegram_alert": false,
  "slack_alert": false,
  "slack_url": "",
  "runner_registration_token": "",
  "max_runner_api_token_age": 0,
  "use_remote_runner": false,
  "git_client_id": "",
  "git_client_secret": "",
  "oidc_providers": {}
}
EOF
chown semaphore:semaphore /opt/semaphore/config.json
chmod 600 /opt/semaphore/config.json
step_complete "$${step}"

step="create-systemd-service"
log "STEP: $${step} - creating systemd service"
cat > /etc/systemd/system/semaphore.service <<'EOF'
[Unit]
Description=Ansible Semaphore
Documentation=https://github.com/ansible-semaphore/semaphore
After=network.target

[Service]
Type=simple
User=semaphore
Group=semaphore
WorkingDirectory=/opt/semaphore
ExecStart=/usr/bin/semaphore server --config /opt/semaphore/config.json
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF
step_complete "$${step}"

step="setup-admin-user"
log "STEP: $${step} - setting up admin user"
# Retrieve password from AWS Secrets Manager
log "Retrieving admin password from Secrets Manager: $${ANSIBLE_PASSWORD_SECRET_NAME}"
set +e
AWS_SECRET_OUTPUT=$(aws secretsmanager get-secret-value \
  --secret-id "$${ANSIBLE_PASSWORD_SECRET_NAME}" \
  --query SecretString \
  --output text \
  --region "$${AWS_REGION}")
AWS_RC=$?
set -e

if [ "$AWS_RC" -ne 0 ] || [ -z "$AWS_SECRET_OUTPUT" ]; then
    log "ERROR: Failed to retrieve password from Secrets Manager. Falling back to autogenerated password"
    SEMAPHORE_PASSWORD=$(openssl rand -base64 16)
else
    log "Successfully retrieved password from Secrets Manager"
    SEMAPHORE_PASSWORD="$AWS_SECRET_OUTPUT"
fi

# Run semaphore setup with BoltDB selected (option 2) and default values for all prompts
{
    echo "2"  # Select BoltDB (option 2)
    echo ""  # db Hostname (default)
    echo ""  # db User (default)
    echo ""  # db Password (default)
    echo ""  # db Name (default)
    echo "/opt/semaphore/playbooks"  # Playbook path
    echo ""  # Public URL (optional)
    echo "no"  # Enable email alerts
    echo "no"  # Enable telegram alerts
    echo "no"  # Enable slack alerts
    echo "no"  # Enable Rocket.Chat alerts
    echo "no"  # Enable Microsoft Team alerts
    echo "no"  # Enable LDAP
    echo "/opt/semaphore"  # Config output directory
    echo "admin"  # Admin username
    echo "$SEMAPHORE_PASSWORD"  # Admin password
    echo "$SEMAPHORE_PASSWORD"  # Confirm password
} | sudo -u semaphore bash -c 'cd /opt/semaphore && semaphore setup --config /opt/semaphore/config.json' || log "Setup completed with exit code $?"
step_complete "$${step}"

step="start-semaphore"
log "STEP: $${step} - starting Semaphore service"
systemctl daemon-reload
systemctl enable semaphore
systemctl start semaphore
step_complete "$${step}"

step="wait-for-semaphore"
log "STEP: $${step} - waiting for Semaphore to be ready"
for i in {1..30}; do
    if curl -s http://localhost:3000 > /dev/null 2>&1; then
        log "Semaphore is ready"
        break
    fi
    log "Waiting for Semaphore to start... attempt $i/30"
    sleep 2
done
step_complete "$${step}"

log "Semaphore installation complete"
log "Access Semaphore at http://<instance-public-ip>:3000"
log "Default credentials will be set during first access or via semaphore user add"
